# Generated by Django 4.0.5 on 2022-06-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_privatepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatepost',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
