# Generated by Django 4.0.5 on 2022-06-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_privatecomments_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomments',
            name='owner',
        ),
    ]
