# Generated by Django 4.0.5 on 2022-06-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_alter_blogpost_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='owner',
        ),
    ]
