# Generated by Django 4.0.5 on 2022-06-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_remove_blogpost_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatepost',
            name='owner',
        ),
    ]
